### ISSUE TITLE
Neo4j schema for best performance

### ISSUE THREAD

**Issue by pawanrawal** [PlatformLab/ldbc-snb-impls#3]
Can someone point me to a schema with the right indexes which would result in most optimal performance for Neo4j. This repository only mentions indexes on the Id field. What are the other fields I should be indexing for best performance?

**Comment by jdellithorpe** [comment]
@pawanrawal Hey sorry didn't see this earlier!

The index creation script is here:

ldbc-snb-impls/snb-interactive-neo4j/scripts/indexCreation.neo4j
